dbfilename redis_cache.rdb
dir /workspace/development/inventory-pos/config/pids
pidfile /workspace/development/inventory-pos/config/pids/redis_cache.pid
bind 127.0.0.1
port 6381
maxmemory 389mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /workspace/development/inventory-pos/config/redis_cache.acl
