dbfilename redis_queue.rdb
dir /workspace/development/inventory-pos/config/pids
pidfile /workspace/development/inventory-pos/config/pids/redis_queue.pid
bind 127.0.0.1
port 6382

aclfile /workspace/development/inventory-pos/config/redis_queue.acl
