dbfilename redis_queue.rdb
dir /workspace/development/firstsite/config/pids
pidfile /workspace/development/firstsite/config/pids/redis_queue.pid
bind 127.0.0.1
port 6379

aclfile /workspace/development/firstsite/config/redis_queue.acl
